<a href='http://www.scienceacademy.ca'> <img style="float: left;height:70px" src="Logo_SA.png"></a>

# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
vector is a 1d
matrix is a 2d

**2. How to import `NumPy` library?** 

In [6]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [7]:
list_1 = [1,2,3,4,5]

In [24]:
array_1=np.array(list_1)
array_1, type(array_1)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

int32


(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [25]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [15]:
np.zeros(5) 

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [13]:
# To avoid overwriting the output, please code here 

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

**8. Generate an array of "5" tens.**

In [29]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

array([ 10.,  10.,  10.,  10.,  10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [34]:
np.arange(50,100,2)

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [38]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [49]:
matrix=np.arange(0,25)
matrix.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
matrix.shape=(5,5)

SyntaxError: unmatched ')' (1665599670.py, line 1)

In [23]:
# To avoid overwriting the output, please code here 

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# To avoid overwriting the output, please code here 

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [59]:
list=np.arange(1,26)
list=list/10
list.reshape(5,5)




array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[ 0.1,  0.2,  0.3,  0.4,  0.5],
       [ 0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5],
       [ 1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [68]:
list=np.linspace(0,24,25) 
list.reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]
Step size is:  1.0


**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
#arnage is 1 int linspace is the differnece of Units 
#arange is steps , linspace is units


**15. How to generate a single random number using NumPy built-in function?**

In [78]:
random=np.random.randn()


0.8085818506914987

array([ 0.55509608])

**16. Write a code to generate a 7x5 matrix of 35 random numbers?** <br>
*Notice, there are no ( ) in the output matrix!*

In [141]:
np.random.rand(35)
    

array([0.24719259, 0.1598918 , 0.33611301, 0.63987944, 0.36438038,
       0.85411604, 0.26576088, 0.41285457, 0.0541354 , 0.06948741,
       0.62975375, 0.08446336, 0.76486121, 0.79727235, 0.55781744,
       0.2304046 , 0.71557739, 0.25797264, 0.12313291, 0.43633082,
       0.15810682, 0.96426588, 0.95316361, 0.49458802, 0.51720121,
       0.45462218, 0.7989251 , 0.30690232, 0.8609416 , 0.49984166,
       0.37332629, 0.34529083, 0.30981716, 0.82690039, 0.86263852])

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [94]:
np.eye(5,5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

**18. Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [101]:
array_2d=np.arange(0,30)
array_2d=array_2d.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [102]:
array_2d[3:,2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [122]:
array_2d[:3,1:2]

array([[ 1],
       [ 6],
       [11]])

In [42]:
#18c:
# To avoid overwriting the output, please code here 

29

In [44]:
#18d:
# To avoid overwriting the output, please code here 

array([[ 1],
       [ 6],
       [11]])

In [46]:
#18e:
# To avoid overwriting the output, please code here 

In [126]:
array_2d[2:3,:]

array([[10, 11, 12, 13, 14]])

In [127]:
array_2d[2:4,:] 

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**19. Can you calculate the sum of all the numbers in array_2d?**

In [129]:
array_2d.sum()

435

435

**20. Calculate sum of all the rows and columns in array_2d.**

In [131]:
list=array_2d[:,:1] 
list.sum()

75

In [132]:
list=array_2d[:1,:]
list.sum()

10

**21. Calculate the standard deviation of the values in array_2d.**

In [137]:
array_2d.std()

8.65544144839919

8.6554414483991895

**22. Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 